#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run only when there are staged changes in frontend/ directory
if git diff --cached --name-only | grep "^frontend/"; then
    cd frontend
    npm run lint
    npm run format
    npm run cypress:run:component -- --quiet
fi
