services:
  backend:
    build:
      context: backend
      target: dev-envs
    restart: always
    secrets:
      - db-password
      - db-user
      - db-database
      - db-host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${FRONTEND_PORT}:3000"
    env_file:
      - .env

  frontend:
    build:
      context: frontend
      target: dev-envs
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  db-password:
    file: db/password.txt
  db-user:
    file: db/user.txt
  db-database:
    file: db/database.txt
  db-host:
    file: db/host.txt
volumes:
  db-data: {}
